# Generated by Django 6.0.6 on 2026-06-30 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database', models.CharField(max_length=255)),
                ('_username', models.CharField(db_column='username', max_length=512)),
                ('_password', models.CharField(db_column='password', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spreadsheet_id', models.CharField(max_length=100)),
                ('sheet_name', models.CharField(max_length=255)),
                ('database_source', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=255)),
                ('sync_mode', models.CharField(choices=[('replace', 'Replace'), ('upsert', 'Upsert')], default='replace', max_length=20)),
                ('key_column', models.CharField(blank=True, default='', max_length=255)),
                ('schedule', models.CharField(help_text="Celery cron expression, e.g. '0 */6 * * *'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('_credentials_json', models.JSONField(blank=True, db_column='credentials_json', default=dict, help_text='Google Service Account credentials (JSON, Fernet-encrypted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_source', models.CharField(help_text="'local' for Nexivo DB or 'external_<id>' for external DBs", max_length=100)),
                ('table_name', models.CharField(help_text="Table name or '*' for all tables", max_length=255)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_schema', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'database_source', 'table_name'],
                'unique_together': {('user', 'database_source', 'table_name')},
            },
        ),
    ]
