# Generated by Django 4.2.30 on 2026-07-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountgroup_created_by_accountgroup_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='updated_by',
        ),
    ]
