# Generated by Django 4.2.30 on 2026-07-19 16:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_seed_default_modules'),
        ('finance', '0003_remove_accountgroup_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. TAXABLE, EXEMPT', max_length=20)),
                ('name', models.CharField(help_text='e.g. مشمول مالیات', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_categories', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. VAT_NORMAL, VAT_EXEMPT', max_length=30)),
                ('name', models.CharField(help_text='e.g. مالیات بر ارزش افزوده عادی', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Tax rate percentage', max_digits=5)),
                ('effective_date', models.DateField(help_text='Date from which this rate applies')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='finance.taxcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions for rule application')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='accounts.company')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='finance.taxcode')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text='e.g. invoice, receipt', max_length=30)),
                ('source_id', models.IntegerField(help_text='ID of the source document')),
                ('base_amount', models.BigIntegerField(help_text='Base amount before tax (Rial)')),
                ('tax_amount', models.BigIntegerField(help_text='Calculated tax amount (Rial)')),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate applied (%)', max_digits=5)),
                ('vat_type', models.CharField(choices=[('output', 'Output VAT (Sales)'), ('input', 'Input VAT (Purchase)'), ('adjustment', 'VAT Adjustment')], default='output', max_length=20)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('posted', 'Posted to GL'), ('reversed', 'Reversed')], default='calculated', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_transactions', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transactions', to='finance.fiscalyear')),
                ('journal_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_transactions', to='finance.journalvoucher')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.taxcode')),
                ('tax_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.taxrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
