# Generated by Django 4.2.30 on 2026-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_taxcategory_taxcode_taxrule_taxtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtransaction',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='ID of the source document', null=True),
        ),
    ]
