# Generated by Django 4.2.30 on 2026-07-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_seed_default_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Purchase Order Approval', max_length=200)),
                ('document_type', models.CharField(help_text='e.g. invoice, purchase_order, production_order', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', '-version'],
                'unique_together': {('company', 'document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. draft, submitted, manager_approval', max_length=100)),
                ('state_type', models.CharField(choices=[('start', 'Start'), ('normal', 'Normal'), ('approval', 'Approval'), ('review', 'Review'), ('waiting', 'Waiting'), ('automated', 'Automated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='normal', max_length=20)),
                ('required_role', models.CharField(blank=True, default='', help_text='Role required to act in this state', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('definition', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. submit, approve, reject, cancel', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_comment', models.BooleanField(default=False, help_text='Mandatory comment on this transition?')),
                ('auto_execute', models.BooleanField(default=False, help_text='Execute automatically without user action?')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.workflowstate')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.workflowstate')),
            ],
            options={
                'ordering': ['action'],
                'unique_together': {('definition', 'source_state', 'action')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('amount_threshold', 'Amount Threshold'), ('role_check', 'Role Check'), ('field_value', 'Field Value'), ('custom', 'Custom Expression')], max_length=30)),
                ('condition', models.JSONField(default=dict, help_text="JSON condition, e.g. {'field': 'total', 'operator': '>', 'value': 5000000}")),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflow.workflowdefinition')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflow.workflowtransition')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('assigned_role', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='accounts.company')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_instances', to='workflow.workflowstate')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowinstance')),
                ('new_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='workflow.workflowstate')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='workflow.workflowstate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.workflowinstance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
