# Generated by Django 4.2.30 on 2026-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_division_user_reports_to_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Unique identifier (e.g. 'marketing')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Display name (e.g. 'بازاریابی')", max_length=100)),
                ('color', models.CharField(default='bg-gray-100 text-gray-700', help_text='Tailwind color classes', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
