# Generated by Django 4.2.30 on 2026-06-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='filter_controls',
            field=models.JSONField(blank=True, default=list, help_text='Persisted dashboard-level filter controls'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('stacked_bar', 'Stacked Bar'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('scatter', 'Scatter Plot'), ('gauge', 'Gauge Chart'), ('table', 'Data Table'), ('kpi', 'KPI Card'), ('heatmap', 'Heatmap'), ('treemap', 'Tree Map')], default='bar', max_length=20),
        ),
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='صفحه ۱', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='widget',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Page this widget belongs to (null = first page for backward compat)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboardpage'),
        ),
    ]
