# Generated by Django 4.2.30 on 2026-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dashboard_filter_controls_alter_widget_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='filter_controls',
            field=models.JSONField(blank=True, default=list, help_text='Persisted page-level filter controls'),
        ),
    ]
