# Generated by Django 4.2.30 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboardpage_filter_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles that can view this page (empty = same as dashboard)'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('stacked_bar', 'Stacked Bar'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('scatter', 'Scatter Plot'), ('gauge', 'Gauge Chart'), ('table', 'Data Table'), ('kpi', 'KPI Card'), ('heatmap', 'Heatmap'), ('treemap', 'Tree Map'), ('sankey', 'Sankey Diagram'), ('funnel', 'Funnel Chart'), ('radar', 'Radar Chart'), ('graph', 'Graph/Network'), ('map', 'Map')], default='bar', max_length=20),
        ),
    ]
