# Generated by Django 4.2.30 on 2026-06-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0004_dashboardpage_allowed_roles_alter_widget_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dashboard_share', 'Dashboard Share'), ('dashboard_create', 'Dashboard Create'), ('dashboard_delete', 'Dashboard Delete'), ('page_access_update', 'Page Access Update'), ('filter_access_update', 'Filter Access Update'), ('user_role_change', 'User Role Change')], max_length=50)),
                ('target_type', models.CharField(help_text='Type of object: dashboard, page, filter_control, user', max_length=50)),
                ('target_id', models.CharField(help_text='ID of the affected object', max_length=100)),
                ('target_name', models.CharField(blank=True, default='', help_text='Human-readable name of the affected object', max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict, help_text='Previous allowed_roles value')),
                ('new_value', models.JSONField(blank=True, default=dict, help_text='New allowed_roles value')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
