# Generated by Django 4.2.30 on 2026-06-25 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0005_add_permission_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_filters', models.JSONField(blank=True, default=list, help_text='Row-level filters enforced for this user on this dashboard')),
                ('visible_pages', models.JSONField(blank=True, default=list, help_text='List of page IDs the user can access (empty = all)')),
                ('visible_filter_controls', models.JSONField(blank=True, default=list, help_text='Filter control IDs the user can use (empty = all)')),
                ('notes', models.TextField(blank=True, default='', help_text='Manager notes about this assignment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Manager who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='User who gets access', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_assignments', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dashboard', 'assigned_to')},
            },
        ),
    ]
