# Generated by Django 4.2.30 on 2026-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_dashboardpage_mobile_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('bar_horizontal', 'Horizontal Bar'), ('stacked_bar', 'Stacked Bar'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('scatter', 'Scatter Plot'), ('gauge', 'Gauge Chart'), ('table', 'Data Table'), ('kpi', 'KPI Card'), ('heatmap', 'Heatmap'), ('treemap', 'Tree Map'), ('sankey', 'Sankey Diagram'), ('funnel', 'Funnel Chart'), ('radar', 'Radar Chart'), ('graph', 'Graph/Network'), ('map', 'Map'), ('leader_kpi', 'Leader KPI')], default='bar', max_length=20),
        ),
    ]
